/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import bitmap.transformer.bitmap.Bitmap;
import org.junit.jupiter.api.Test;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

class AppTest {

    @Test
    void testForGreyScale(){
        String userPath = System.getProperty("user.dir");
        System.out.println(userPath);
        String resourcesPath;
        String targetGrayFileName = "test-gray.bmp";
        String inputFileName = "red_100x100.bmp";
        String outputFileName = "grey-output.bmp";
        if (userPath.endsWith("bitmap-transformer")) {
            resourcesPath = "app/src/test/resources/";
        } else {
            resourcesPath = "src/test/resources/";
        }
        File inputImageFile = new File(resourcesPath + inputFileName);
        File targetGrayFile = new File(resourcesPath + targetGrayFileName);
        BufferedImage inputBufferedImage = null;
        BufferedImage targetGrayBufferedImage = null;
        try{
            inputBufferedImage = ImageIO.read(inputImageFile);
            targetGrayBufferedImage = ImageIO.read(targetGrayFile);
            Bitmap inputBitmap = new Bitmap(inputBufferedImage);
            inputBitmap.grayScaleTransform();
            inputBitmap.writeOutImage(resourcesPath + outputFileName);
            Color outputColor = new Color(inputBitmap.getOutputBufferedImage().getRGB(0, 0));
            Color testGrayColor = new Color(targetGrayBufferedImage.getRGB(0, 0));
            assert(outputColor.getRed() == testGrayColor.getRed());
        } catch (IOException ioe) {
            ioe.printStackTrace();
            System.exit(1);
        }
    }
}