/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Path fileToProcess;
        if (args.length > 0)
            fileToProcess = Paths.get(args[0]).toAbsolutePath();
        else
            fileToProcess = Paths.get("./app/src/main/resources/gates.js");
        lintJavaScriptFile(fileToProcess);
    }

    public static ArrayList<Integer> lintJavaScriptFile(Path javaScriptFilePath) {
        ArrayList<Integer> errorLines = new ArrayList<>();
        try{
            Scanner gatesScanner = new Scanner(javaScriptFilePath);
            int lineNumber = 0;
            while(gatesScanner.hasNextLine()) {
                String next = gatesScanner.nextLine();
                lineNumber++;
                boolean shouldSkip = next.equals("") || next.contains("if") || next.contains("else") || next.endsWith("{") || next.endsWith("}");
                if (!shouldSkip && !next.endsWith(";")) {
                    errorLines.add(lineNumber);
                    System.out.println("Line " + lineNumber + " Missing Semicolon.");
                }
            }
            System.out.println("Number of errors: " + errorLines.size());
        } catch (IOException ioe) {
            ioe.printStackTrace();
            System.exit(1);
        }
        return errorLines;
    }
}
