/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmapTransformer;

import bitmapTransformer.bitmap.Bitmap;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Arrays;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        String userPath = System.getProperty("user.dir");
        String resourcesPath = "";
        String inputFileName = "";
        String outputFileName = "";
        String transformationType = "";
        try {
            inputFileName = args[0];
            outputFileName = args[1];
            transformationType = args[2];
        } catch (IndexOutOfBoundsException oob) {
            oob.printStackTrace();
            System.out.println("This application requires 3 arguments.");
            System.exit(1);
        }
        if (userPath.endsWith("bitmapTransformer")) {
            resourcesPath = "app/src/main/resources/";
        } else {
            resourcesPath = "src/main/resources/";
        }
        File inputImageFile = new File(resourcesPath + inputFileName);
        Bitmap bitmapToTransform = new Bitmap(inputImageFile);
        System.out.println("Transform complete, " + outputFileName + " available in resources directory.");
        //bitmapToTransform.writeOutImage(resourcesPath + outputFileName);
    }
}
