/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.nio.file.Paths;

class AppTest {
    @Test
    void test_linter() {
        System.out.println(System.getProperty("user.dir"));
        Path noErrorFile = Paths.get("./src/main/resources/noError.js");
        Path oneErrorFile = Paths.get("./src/main/resources/oneError.js");
        Path fewErrorFile = Paths.get("./src/main/resources/fewError.js");
        Path manyErrorFile = Paths.get("./src/main/resources/gates.js");
        Path emptyFile = Paths.get("./src/main/resources/empty.js");
        System.out.println("Processing No-Error File...");
        assert(App.lintJavaScriptFile(noErrorFile).size() == 0);
        System.out.println("Processing One-Error File...");
        assert(App.lintJavaScriptFile(oneErrorFile).size() == 1);
        System.out.println("Processing Few-Errors File...");
        assert(App.lintJavaScriptFile(fewErrorFile).size() == 3);
        System.out.println("Processing Many-Errors File...");
        assert(App.lintJavaScriptFile(manyErrorFile).size() == 46);
        System.out.println("Processing Empty File...");
        assert(App.lintJavaScriptFile(emptyFile).size() == 0);
    }
}
